version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./iotserver/db/data:/var/lib/postgresql/data
  broker:
    image: eclipse-mosquitto:2.0
    container_name: my-mosquitto-broker
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./iotbridge/mosquitto/config:/mosquitto/config
      - ./iotbridge/mosquitto/data:/mosquitto/data
      - ./iotbridge/mosquitto/log:/mosquitto/log  