[project]
name = "iotserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anyio>=4.11.0",
    "azure-eventhub>=5.15.1",
    "azure-iot-hub>=2.7.0",
    "fastapi[standard]>=0.121.0",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.12.4",
    "python-dotenv>=1.2.1",
    "six>=1.17.0",
    "sqlalchemy>=2.0.44",
    "uamqp>=1.6.11",
]
